const KEY = 'etsy-money-map-v1';
const nav = [['home','Home'],['sales','Sales'],['expenses','Expenses'],['products','Products'],['reports','Reports'],['mentor','Mentor'],['settings','Settings']];
const titles = {home:['Overview','Your shop money, at a glance.'],sales:['Sales','Log each sale to keep profit accurate.'],expenses:['Expenses','Track what it takes to run your shop.'],products:['Products','See which listings truly earn their keep.'],reports:['Reports','Your month, explained in plain English.'],mentor:['Mentor','Useful prompts built from your shop numbers.'],settings:['Settings','Currency, fee assumptions, and backups.']};
const cats=['Materials','Shipping Supplies','Software / Tools','Advertising','Other'];
const today=()=>new Date().toISOString().slice(0,10);
const blank=()=>({screen:'home',onboarded:false,demo:false,currency:'$',fee:{transaction:6.5,payment:3,listing:.2},products:[],sales:[],expenses:[]});
const demo=()=>({products:[{id:'p1',name:'Boho Wall Art (Digital)',cost:.5,labor:2,price:12},{id:'p2',name:'Custom Pet Portrait',cost:3,labor:15,price:35},{id:'p3',name:'Ceramic Mug (POD)',cost:6.5,labor:3,price:15},{id:'p4',name:'Canvas Tote Bag',cost:9,labor:4,price:14}],sales:[['s1','2026-09-02','p1',12,1.34],['s2','2026-09-03','p2',35,3.53],['s3','2026-09-05','p3',15,1.63],['s4','2026-09-06','p1',12,1.34],['s5','2026-09-09','p4',14,1.53],['s6','2026-09-12','p2',35,3.53],['s7','2026-09-15','p1',12,1.34],['s8','2026-09-20','p3',15,1.63]].map(([id,date,productId,price,fee])=>({id,date,productId,price,fee})),expenses:[{id:'e1',date:'2026-09-01',category:'Materials',amount:45,note:'Cardstock, ink, mugs'},{id:'e2',date:'2026-09-04',category:'Advertising',amount:60,note:'Etsy Ads'},{id:'e3',date:'2026-09-08',category:'Software / Tools',amount:20,note:'Canva + Printify'},{id:'e4',date:'2026-09-11',category:'Shipping Supplies',amount:18,note:'Boxes and mailers'}]});
let state; try { state={...blank(),...JSON.parse(localStorage.getItem(KEY)||'{}')}; } catch { state=blank(); }
const app=document.querySelector('#app');
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function money(value){const n=Number(value)||0;return `${n<0?'-':''}${state.currency}${Math.abs(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;}
function totals(){const sales=state.sales.reduce((n,s)=>n+s.price,0),fees=state.sales.reduce((n,s)=>n+s.fee,0),expenses=state.expenses.reduce((n,e)=>n+e.amount,0);return {sales,fees,expenses,profit:sales-fees-expenses};}
function product(id){return state.products.find(p=>p.id===id)}
function margin(p){return p.price?((p.price-p.cost-p.labor)/p.price)*100:0}
function status(p){const m=margin(p);return m>=40?['Winner','winner']:m>=20?['Watch','watch']:m>0?['Fix','fix']:['Pause','pause']}
function toast(msg){document.querySelector('.toast')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="toast">${msg}</div>`);setTimeout(()=>document.querySelector('.toast')?.remove(),2200)}
function metric(label,value,klass=''){return `<div class="metric"><label>${label}</label><strong class="${klass}">${value}</strong></div>`}
function navHtml(){return nav.map(([id,label])=>`<button data-screen="${id}" class="${state.screen===id?'active':''}"><i></i>${label}</button>`).join('')}
function pageHeader(){const [label,sub]=titles[state.screen];return `<div class="page-top"><div><div class="eyebrow">MoneyMap OS</div><h1>${label}</h1><p>${sub}</p></div><button class="help" data-help title="How this screen works">?</button></div>${state.demo?'<div class="demo"><span>You are exploring <strong>demo data</strong>. It is not your real shop record.</span><button data-blank>Use my own data</button></div>':''}`}
function home(){const t=totals(),rows=[...state.products].sort((a,b)=>margin(b)-margin(a)),best=rows[0],worst=rows.length>1?rows.at(-1):null;let actions=[];if(!state.products.length)actions.push('Add your first product to start tracking real margins.');if(t.profit<0)actions.push('Your shop lost money this period. Check advertising and materials spend.');state.products.filter(p=>margin(p)<20).slice(0,2).forEach(p=>actions.push(`Raise the price or lower costs on “${p.name}” — its margin is ${margin(p).toFixed(0)}%.`));if(!state.sales.length)actions.push('Log your first sale to start seeing real profit.');while(actions.length<3)actions.push('Export a backup before your next big sales day.');return `<div class="metrics">${metric('Net profit',money(t.profit),t.profit>=0?'good':'bad')}${metric('Total sales',money(t.sales))}${metric('Etsy fees',money(t.fees))}${metric('Expenses',money(t.expenses))}</div><div class="home-grid">${best?`<div class="insight success"><label>Best seller</label><strong>${best.name}</strong><span>${margin(best).toFixed(0)}% margin</span></div>`:''}${worst?`<div class="insight warning"><label>Needs attention</label><strong>${worst.name}</strong><span>${margin(worst).toFixed(0)}% margin</span></div>`:''}</div><div class="panel"><h2>Your next 3 actions</h2><ol class="actions">${actions.slice(0,3).map((x,i)=>`<li><b>${i+1}</b><span>${x}</span></li>`).join('')}</ol></div>`}
function sales(){return `<div class="panel"><h2>Log a sale</h2><p class="intro">Record a completed order and MoneyMap will update profit instantly.</p><form id="sale-form" class="form-grid"><label class="field">Date<input name="date" type="date" value="${today()}"></label><label class="field">Product<select name="productId"><option value="">Choose product</option>${state.products.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></label><label class="field">Sale price<input name="price" type="number" min="0" step=".01" placeholder="0.00"></label><label class="field">Etsy fee <input name="fee" type="number" min="0" step=".01" placeholder="Auto"></label></form><div class="form-action"><button class="button" form="sale-form">Add sale</button></div></div>${state.sales.length?`<div class="records">${state.sales.map(s=>{const p=product(s.productId);return `<div class="record"><div><div class="record-title">${p?.name||'Deleted product'}</div><div class="record-sub">${s.date} · fee ${money(s.fee)}</div></div><div class="record-end"><div class="amount">${money(s.price)}<small>net ${money(s.price-s.fee)}</small></div><button class="delete" data-delete-sale="${s.id}">Delete</button></div></div>`}).join('')}</div>`:'<div class="empty">No sales yet. Add a product, then log your first sale.</div>'}`}
function expenses(){return `<div class="panel"><h2>Add an expense</h2><p class="intro">Materials, tools, ads, and the costs that shape your actual profit.</p><form id="expense-form" class="form-grid"><label class="field">Date<input name="date" type="date" value="${today()}"></label><label class="field">Category<select name="category">${cats.map(c=>`<option>${c}</option>`).join('')}</select></label><label class="field">Amount<input name="amount" type="number" min="0" step=".01" placeholder="0.00"></label><label class="field">Note<input name="note" placeholder="Optional"></label></form><div class="form-action"><button class="button" form="expense-form">Add expense</button></div></div>${state.expenses.length?`<div class="records">${state.expenses.map(e=>`<div class="record"><div><div class="record-title">${e.category}</div><div class="record-sub">${e.date}${e.note?' · '+e.note:''}</div></div><div class="record-end"><div class="amount">${money(e.amount)}</div><button class="delete" data-delete-expense="${e.id}">Delete</button></div></div>`).join('')}</div>`:'<div class="empty">No expenses logged yet.</div>'}`}
function products(){return `<div class="panel"><h2>Add a product</h2><p class="intro">Include material and labor costs to see the real margin on every listing.</p><form id="product-form" class="form-grid"><label class="field">Name<input name="name" placeholder="e.g. Boho print"></label><label class="field">Material cost<input name="cost" type="number" min="0" step=".01" placeholder="0.00"></label><label class="field">Labor cost<input name="labor" type="number" min="0" step=".01" placeholder="0.00"></label><label class="field">Sale price<input name="price" type="number" min="0" step=".01" placeholder="0.00"></label></form><div class="form-action"><button class="button" form="product-form">Add product</button></div></div>${state.products.length?`<div class="records">${state.products.map(p=>{const [s,c]=status(p);return `<div class="record"><div><div class="record-title">${p.name}</div><div class="record-sub">Cost ${money(p.cost)} + labor ${money(p.labor)} · price ${money(p.price)}</div></div><div class="record-end"><div class="amount">${margin(p).toFixed(0)}%<small>margin</small></div><span class="badge ${c}">${s}</span><button class="delete" data-delete-product="${p.id}">Delete</button></div></div>`}).join('')}</div>`:'<div class="empty">No products yet. Add one to see its real margin.</div>'}`}
function reports(){const t=totals(),by={};state.expenses.forEach(e=>by[e.category]=(by[e.category]||0)+e.amount);const max=Math.max(...Object.values(by),1);return `<div class="summary-grid">${metric('Sales',money(t.sales))}${metric('Fees',money(t.fees))}${metric('Expenses',money(t.expenses))}${metric('Net profit',money(t.profit),t.profit>=0?'good':'bad')}</div><div class="panel"><h2>Expense breakdown</h2>${Object.keys(by).length?Object.entries(by).map(([k,v])=>`<div class="bar-row"><div class="bar-label"><b>${k}</b><span>${money(v)}</span></div><div class="bar"><span style="width:${v/max*100}%"></span></div></div>`).join(''):'<p class="intro">No expenses logged yet.</p>'}</div><div class="panel"><h2>Product profitability</h2>${state.products.length?state.products.map(p=>{const[s,c]=status(p);return `<div class="record"><span class="record-title">${p.name}</span><div class="record-end"><span class="record-sub">${margin(p).toFixed(0)}%</span><span class="badge ${c}">${s}</span></div></div>`}).join(''):'<p class="intro">Add products to compare their margins.</p>'}</div>`}
function mentor(){const t=totals(),weak=[...state.products].sort((a,b)=>margin(a)-margin(b))[0];const prompts=[['Profit coach','Get a simple view of whether your shop is truly profitable.',`You are my Etsy shop profit coach. This period: sales ${money(t.sales)}, Etsy fees ${money(t.fees)}, expenses ${money(t.expenses)}, net profit ${money(t.profit)}. Tell me if my shop is actually profitable and give me 3 clear next steps.`],['Pricing coach','Find out which listing might be priced too low.',`You are my Etsy pricing coach. My weakest-margin product is "${weak?.name||'N/A'}" at ${weak?margin(weak).toFixed(0)+'%':'N/A'} margin. Suggest a new price and explain it simply.`],['Product doctor','Decide which products to fix, watch, or pause.',`You are my Etsy product doctor. Here are my products and margins: ${state.products.map(p=>`${p.name} (${margin(p).toFixed(0)}%)`).join(', ')||'No products yet'}. Tell me what to fix, watch, or pause and why.`],['Monthly review','Turn the numbers into a short, encouraging review.',`Write me a short encouraging Etsy shop review. Sales ${money(t.sales)}, fees ${money(t.fees)}, expenses ${money(t.expenses)}, net profit ${money(t.profit)}. Keep it simple and actionable.`]];return `<div class="mentor">${prompts.map(([a,b,c])=>`<div class="panel"><div class="mentor-head"><div><h2>${a}</h2><p class="intro">${b}</p></div><button class="button ghost" data-copy="${encodeURIComponent(c)}">Copy prompt</button></div></div>`).join('')}</div>`}
function settings(){return `<div class="settings-grid"><div class="panel"><h2>Currency</h2><p class="intro">How amounts appear throughout your dashboard.</p><select id="currency"><option value="$">$ USD/CAD/AUD</option><option value="€">€ EUR</option><option value="£">£ GBP</option></select></div><div class="panel"><h2>Fee assumptions</h2><p class="intro">Used to suggest Etsy fees for new sales.</p><div class="form-grid"><label class="field">Transaction %<input id="tx" type="number" value="${state.fee.transaction}"></label><label class="field">Payment %<input id="payment" type="number" value="${state.fee.payment}"></label><label class="field">Listing fee<input id="listing" type="number" step=".01" value="${state.fee.listing}"></label></div><div class="form-action"><button class="button" data-save-fees>Save fees</button></div></div><div class="panel"><h2>Backup & data</h2><p class="intro">Your records live in this browser. Keep a backup.</p><button class="button" data-export>Export my data</button> <label class="button secondary" style="display:inline-block">Import data<input id="import" type="file" accept="application/json" hidden></label></div><div class="panel"><h2>Workspace</h2><p class="intro">${state.demo?'You are currently exploring demo data.':'Want to see how it works with sample numbers?'}</p><button class="button ghost" data-${state.demo?'blank':'demo'}>${state.demo?'Switch to my own workspace':'Load demo data'}</button></div><div class="panel"><h2 style="color:var(--red)">Clear all data</h2><p class="intro">Permanently erase sales, expenses, and products in this browser.</p><button class="button danger" data-reset>Clear all data</button></div><div class="panel"><h2>Privacy & data</h2><p class="note">Data stays in your browser. No login is required. Export a backup whenever you like. Reports are planning tools, not tax advice.</p></div></div>`}
function content(){return {home,sales,expenses,products,reports,mentor,settings}[state.screen]();}
function render(){app.innerHTML=`<div class="shell"><aside class="side"><div class="brand"><div class="brand-mark"><span class="brand-icon"></span>MoneyMap OS</div><p>Your Etsy shop, in plain English.</p></div><nav class="nav">${navHtml()}</nav><div class="saved">Saved in this browser</div></aside><main>${pageHeader()}${content()}</main><nav class="mobile-nav">${navHtml()}</nav></div>${!state.onboarded?onboarding():''}`;document.querySelector('#currency')&&(document.querySelector('#currency').value=state.currency)}
function onboarding(){return `<div class="overlay"><div class="modal"><h2>Welcome to MoneyMap OS</h2><p>Track sales, expenses, and real profit for your Etsy shop. Choose how you want to begin.</p><div class="modal-actions"><button class="button" data-demo>Try it with demo data</button><button class="button secondary" data-blank>Start with a blank shop</button></div></div></div>`}
function fee(price){return +(price*((state.fee.transaction+state.fee.payment)/100)+state.fee.listing).toFixed(2)}
document.addEventListener('click',e=>{const screen=e.target.closest('[data-screen]');if(screen){state.screen=screen.dataset.screen;render()}if(e.target.closest('[data-demo]')){state={...state,...demo(),onboarded:true,demo:true};save();render();toast('Demo data loaded')}if(e.target.closest('[data-blank]')){state={...blank(),onboarded:true};save();render();toast('Your blank workspace is ready')}if(e.target.closest('[data-help]'))toast('Your data stays in this browser. Add products, log sales and expenses, then review your profit.')
if(e.target.closest('[data-delete-sale]')){state.sales=state.sales.filter(x=>x.id!==e.target.closest('[data-delete-sale]').dataset.deleteSale);save();render()}if(e.target.closest('[data-delete-expense]')){state.expenses=state.expenses.filter(x=>x.id!==e.target.closest('[data-delete-expense]').dataset.deleteExpense);save();render()}if(e.target.closest('[data-delete-product]')){state.products=state.products.filter(x=>x.id!==e.target.closest('[data-delete-product]').dataset.deleteProduct);save();render()}if(e.target.closest('[data-copy]'))navigator.clipboard.writeText(decodeURIComponent(e.target.closest('[data-copy]').dataset.copy)).then(()=>toast('Prompt copied'))
if(e.target.closest('[data-save-fees]')){state.fee={transaction:+document.querySelector('#tx').value||0,payment:+document.querySelector('#payment').value||0,listing:+document.querySelector('#listing').value||0};save();toast('Fee assumptions saved')}if(e.target.closest('[data-export]')){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='moneymap-backup.json';a.click();toast('Backup downloaded')}if(e.target.closest('[data-reset]')){if(confirm('Clear all sales, expenses, and products?')){state={...blank(),onboarded:true};save();render();toast('All data cleared')}}});
document.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);if(e.target.id==='product-form'){if(!f.get('name')||!f.get('price'))return toast('Add a name and price first');state.products.unshift({id:crypto.randomUUID(),name:f.get('name'),cost:+f.get('cost')||0,labor:+f.get('labor')||0,price:+f.get('price')||0});toast('Product added')}if(e.target.id==='expense-form'){if(!f.get('amount'))return toast('Enter an amount first');state.expenses.unshift({id:crypto.randomUUID(),date:f.get('date'),category:f.get('category'),amount:+f.get('amount'),note:f.get('note')});toast('Expense added')}if(e.target.id==='sale-form'){if(!f.get('productId')||!f.get('price'))return toast('Choose a product and price first');const price=+f.get('price');state.sales.unshift({id:crypto.randomUUID(),date:f.get('date'),productId:f.get('productId'),price,fee:f.get('fee')===''?fee(price):+f.get('fee')});toast('Sale added')}save();render()});
document.addEventListener('change',e=>{if(e.target.id==='currency'){state.currency=e.target.value;save();render()}if(e.target.id==='import'){const r=new FileReader();r.onload=()=>{try{state={...blank(),...JSON.parse(r.result),onboarded:true,demo:false};save();render();toast('Data imported')}catch{toast('Could not read that file')}};r.readAsText(e.target.files[0])}});render();
